export const COMICS_RESULTS = 'COMICS_RESULTS';
export const COMICS_CHARACTERS = 'COMICS_CHARACTERS';
export const EMAIL_SENT = 'EMAIL_SENT';
export const LOADING_COMICS = 'LOADING_COMICS';
export const LOADING_CHARACTERS = 'LOADING_CHARACTERS';